# .github/workflows/release.yml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/batonogov/pyinstaller-linux:latest
          options: |
            --platform linux/arm64
            --volume ${{ github.workspace }}/:/src
          run: |
            pip install -r /src/requirements.txt
            pyinstaller --onefile /src/src/app.py

      - name: Bundle App
        run: |
          mkdir -p .artie && \
          cp -r ./dist/app ./assets ./config.json .artie
          zip -r Artie.zip .artie ./Artie\ Scraper.sh

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: Artie.zip
